version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
    command: ["npm","run","start"]
    environment:
      - NODE_ENV=production
